export const benchmarkTable = [
  {
    model: "QSVM",
    roc_auc: 0.984,
    precision: 0.91,
    recall: 0.88,
    f1: 0.895,
    status: "available" as const,
    note: "Primary model on the shared evaluation split",
  },
  {
    model: "XGBoost",
    roc_auc: 0.986,
    precision: 0.92,
    recall: 0.87,
    f1: 0.894,
    status: "available" as const,
    note: "Classical baseline",
  },
  {
    model: "Random Forest",
    roc_auc: 0.981,
    precision: 0.9,
    recall: 0.85,
    f1: 0.874,
    status: "available" as const,
    note: "Classical baseline",
  },
  {
    model: "Logistic Regression",
    roc_auc: 0.972,
    precision: 0.84,
    recall: 0.81,
    f1: 0.825,
    status: "available" as const,
    note: "Classical baseline",
  },
  {
    model: "RBF-SVM",
    roc_auc: null,
    precision: null,
    recall: null,
    f1: null,
    status: "unavailable" as const,
    note: "Not returned by the benchmark job",
  },
];

export const featureSchema = [
  {
    key: "amount",
    label: "Transaction amount",
    type: "number" as const,
    unit: "KES",
    required: true,
    min: 0,
    max: 500000,
    placeholder: "e.g. 18500",
    description: "Synthetic amount in Kenyan shillings",
  },
  {
    key: "oldbalanceOrg",
    label: "Origin balance before",
    type: "number" as const,
    unit: "KES",
    required: true,
    min: 0,
    max: 5000000,
    placeholder: "e.g. 22000",
    description: "Balance before the transaction",
  },
  {
    key: "newbalanceOrig",
    label: "Origin balance after",
    type: "number" as const,
    unit: "KES",
    required: true,
    min: 0,
    max: 5000000,
    placeholder: "e.g. 3500",
    description: "Balance after the transaction",
  },
  {
    key: "oldbalanceDest",
    label: "Destination balance before",
    type: "number" as const,
    unit: "KES",
    required: true,
    min: 0,
    max: 5000000,
    placeholder: "e.g. 1400",
    description: "Destination balance before the transaction",
  },
  {
    key: "newbalanceDest",
    label: "Destination balance after",
    type: "number" as const,
    unit: "KES",
    required: true,
    min: 0,
    max: 5000000,
    placeholder: "e.g. 19900",
    description: "Destination balance after the transaction",
  },
  {
    key: "transactionType",
    label: "Transaction type",
    type: "select" as const,
    unit: null,
    required: true,
    min: null,
    max: null,
    placeholder: null,
    description: "Synthetic transaction category",
    options: [
      { label: "Cash out", value: "CASH_OUT" },
      { label: "Transfer", value: "TRANSFER" },
      { label: "Payment", value: "PAYMENT" },
      { label: "Cash in", value: "CASH_IN" },
    ],
  },
];

export const modelConfig = {
  primary_model: "QSVM · RBF kernel",
  supported_models: ["QSVM", "Logistic Regression", "Random Forest", "XGBoost", "RBF-SVM"],
  feature_schema: featureSchema,
  threshold_config: {
    review_recommended: 0.45,
    high_risk_signal: 0.75,
    note: "Thresholds are demo guidance, not enforcement policy",
  },
  metadata: {
    dataset: "PaySim-derived synthetic transactions",
    schema_version: "fraud-busters-4-8-feature-v1",
    quantum_backend: "Simulator rehearsal",
  },
};