import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { useEffect, useState, type ChangeEvent, type FormEvent, type ReactNode } from "react";
import { Link, Route, Switch, useLocation } from "wouter";
import { Activity, ArrowRight, BarChart3, Check, CircleAlert, Cpu, FlaskConical, Gauge, Hexagon, Home as HomeIcon, Info, Menu, Play, RotateCcw, ShieldCheck, SlidersHorizontal } from "lucide-react";
import { getGetBenchmarksQueryKey, getGetModelConfigQueryKey, getGetOverviewQueryKey, useAnalyzeTransaction, useGetBenchmarks, useGetModelConfig, useGetOverview, useHealthCheck } from "@workspace/api-client-react";
import type { AnalyzeResponse, BenchmarkRow, FeatureDefinition } from "@workspace/api-client-react";
import { Button } from "@workspace/fraud-busters-command-center/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@workspace/fraud-busters-command-center/components/ui/card";
import { Badge } from "@workspace/fraud-busters-command-center/components/ui/badge";
import { Input } from "@workspace/fraud-busters-command-center/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@workspace/fraud-busters-command-center/components/ui/select";
import { Label } from "@workspace/fraud-busters-command-center/components/ui/label";
import { Skeleton } from "@workspace/fraud-busters-command-center/components/ui/skeleton";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@workspace/fraud-busters-command-center/components/ui/table";
import { TooltipProvider } from "@workspace/fraud-busters-command-center/components/ui/tooltip";
import { Toaster } from "@workspace/fraud-busters-command-center/components/ui/toaster";
import NotFound from "@/pages/not-found";

const queryClient = new QueryClient();
const nav = [{ href:"/", label:"Overview", icon:HomeIcon }, { href:"/analyze", label:"Live analysis", icon:Activity }, { href:"/benchmarks", label:"Benchmarks", icon:BarChart3 }, { href:"/methodology", label:"Methodology", icon:Info }, { href:"/demo", label:"Demo scenarios", icon:Play }];

function Shell({ children }: { children: ReactNode }) {
  const [location] = useLocation(); const [open,setOpen] = useState(false);
  return <div className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-20 border-b bg-sidebar/95 backdrop-blur">
      <div className="mx-auto flex h-16 max-w-screen-2xl items-center justify-between px-4 md:px-8">
        <Link href="/" className="flex items-center gap-3" data-testid="link-brand"><span className="flex size-9 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Hexagon className="size-5" /></span><span><span className="block text-sm font-bold tracking-tight">FRAUD BUSTERS</span><span className="block text-[10px] uppercase tracking-[.2em] text-muted-foreground">Command center</span></span></Link>
        <button className="rounded-md p-2 md:hidden" onClick={()=>setOpen(!open)} aria-label={open?"Close navigation":"Open navigation"} aria-expanded={open} data-testid="button-menu"><Menu className="size-5"/></button>
        <nav aria-label="Primary navigation" className={`${open?"flex":"hidden"} absolute left-0 top-16 w-full flex-col gap-1 border-b bg-sidebar p-3 md:static md:flex md:w-auto md:flex-row md:border-0 md:bg-transparent md:p-0`}>{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} onClick={()=>setOpen(false)} data-testid={`link-nav-${label.toLowerCase().replaceAll(" ","-")}`} className={`flex items-center gap-2 rounded-md px-3 py-2 text-sm transition-colors hover:bg-sidebar-accent ${location===href?"bg-sidebar-accent font-semibold text-primary":"text-sidebar-foreground"}`}><Icon className="size-4"/>{label}</Link>)}</nav>
      </div>
    </header>
    <main className="mx-auto max-w-screen-2xl px-4 py-6 md:px-8 md:py-10">{children}</main>
    <footer className="mx-auto flex max-w-screen-2xl flex-col gap-2 border-t px-4 py-5 text-xs text-muted-foreground md:flex-row md:justify-between md:px-8"><span>Fraud Busters · Synthetic evaluation environment</span><span className="flex items-center gap-2"><span className="size-2 rounded-full bg-primary"/> Human review remains the decision point</span></footer>
  </div>
}

function StateBadge({ value }: { value?: string }) { const v=value||"unknown"; const tone=v==="live"||v==="ready"?"bg-primary/10 text-primary":v==="fallback"||v==="unavailable"?"bg-destructive/10 text-destructive":"bg-accent/30 text-accent-foreground"; return <Badge className={tone} data-testid={`status-${v}`}>{v}</Badge> }
function PageTitle({ eyebrow,title,description,action }: {eyebrow:string,title:string,description:string,action?:ReactNode}) { useEffect(()=>{ document.title=`${title} · Fraud Busters`; const meta=document.querySelector('meta[name="description"]'); if(meta) meta.setAttribute("content",description); },[title,description]); return <div className="mb-8 flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><div className="mb-2 flex items-center gap-2 text-xs font-bold uppercase tracking-[.18em] text-primary"><span className="size-1.5 rounded-full bg-primary"/>{eyebrow}</div><h1 className="text-3xl font-bold tracking-tight md:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">{description}</p></div>{action}</div> }
function Loading({ label="Loading intelligence" }: {label?:string}) { return <Card><CardContent className="space-y-4 p-6"><Skeleton className="h-5 w-1/3"/><Skeleton className="h-10 w-2/3"/><p className="text-xs text-muted-foreground">{label}…</p></CardContent></Card> }
function ErrorState({ retry }: {retry:()=>void}) { return <Card className="border-destructive/40"><CardContent className="flex items-center gap-4 p-6"><CircleAlert className="size-7 text-destructive"/><div className="flex-1"><p className="font-semibold">Intelligence service unavailable</p><p className="text-sm text-muted-foreground">No raw service details are shown. Try again or continue in rehearsal mode.</p></div><Button variant="outline" onClick={retry} data-testid="button-retry"><RotateCcw className="mr-2 size-4"/>Retry</Button></CardContent></Card> }
function ScoreCard({ result }: {result?: AnalyzeResponse}) { if(!result) return <Card className="data-grid"><CardContent className="p-8"><Gauge className="mb-4 size-8 text-muted-foreground"/><p className="font-semibold">No analysis yet</p><p className="mt-1 text-sm text-muted-foreground">Submit a synthetic transaction to see a model score.</p></CardContent></Card>; const score=Math.round(result.fraud_score*100); const high=score>=70; return <Card className="overflow-hidden"><div className={`h-1 ${high?"bg-destructive":"bg-accent"}`}/><CardContent className="p-6"><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-widest text-muted-foreground">Model score</p><div className={`mt-2 text-7xl font-bold tracking-tighter ${high?"text-destructive":"text-primary"}`} data-testid="text-fraud-score">{score}<span className="text-3xl">%</span></div></div><StateBadge value={result.execution_mode}/></div><div className="mt-5 flex items-center justify-between border-t pt-4 text-sm"><span className="text-muted-foreground">Risk band</span><strong data-testid="text-risk-band">{result.risk_band||"Review signal"}</strong></div><p className="mt-4 rounded-md bg-muted p-3 text-xs leading-relaxed text-muted-foreground">This score signals review priority. It is not proof of fraud and does not trigger automatic enforcement.</p></CardContent></Card> }

function Home() { const q=useGetOverview({query:{queryKey:getGetOverviewQueryKey()}}); const h=useHealthCheck(); const d=q.data; return <><PageTitle eyebrow="Operational overview" title="See the signal. Keep the human in the loop." description="A calm workspace for inspecting one synthetic transaction at a time, with model identity and execution state visible at every step." action={<Link href="/analyze" className="inline-flex"><Button data-testid="button-start-analysis">Start live analysis <ArrowRight className="ml-2 size-4"/></Button></Link>}/>{q.isLoading?<Loading/>:q.isError?<ErrorState retry={()=>q.refetch()}/>:<><div className="grid gap-4 md:grid-cols-4"><Metric label="System status" value={d?.system_status||"unavailable"} icon={<ShieldCheck/>} test="status-system"/><Metric label="Execution mode" value={d?.execution_mode||"unknown"} icon={<Cpu/>} test="status-execution"/><Metric label="Primary model" value={d?.primary_model||"Not reported"} icon={<SlidersHorizontal/>} test="text-primary-model"/><Metric label="Last benchmark" value={d?.last_benchmark?"Available":"Unavailable"} icon={<BarChart3/>} test="text-last-benchmark"/></div><div className="mt-6 grid gap-6 lg:grid-cols-[1.2fr_.8fr]"><ScoreCard result={d?.latest_analysis}/><Card><CardHeader><CardTitle className="text-base">System posture</CardTitle></CardHeader><CardContent className="space-y-4 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Health check</span><StateBadge value={h.data?.status||"pending"}/></div><div className="flex justify-between"><span className="text-muted-foreground">Latest request</span><span className="font-mono text-xs">{d?.latest_analysis?.request_id||"None recorded"}</span></div><div className="rounded-md border border-accent/50 bg-accent/10 p-3 text-xs leading-relaxed">The command center is designed for evaluation and rehearsal. Model output supports analyst judgment; it does not make a guilt determination.</div></CardContent></Card></div></>}</> }
function Metric({label,value,icon,test}:{label:string,value:string,icon:React.ReactNode,test:string}) { return <Card><CardContent className="flex items-center gap-4 p-5"><span className="flex size-10 items-center justify-center rounded-lg bg-primary/10 text-primary">{icon}</span><div className="min-w-0"><p className="text-xs text-muted-foreground">{label}</p><p className="truncate text-lg font-bold" data-testid={test}>{value}</p></div></CardContent></Card> }

function Analyze() { const cfg=useGetModelConfig({query:{queryKey:getGetModelConfigQueryKey()}}); const mutation=useAnalyzeTransaction(); const [values,setValues]=useState<Record<string,string>>({}); const schema=cfg.data?.feature_schema||[]; const submit=(e:FormEvent)=>{e.preventDefault(); const transaction=Object.fromEntries(schema.map(f=>[f.key,f.type==="number"?Number(values[f.key]||0):values[f.key]||""])); mutation.mutate({data:{transaction}})}; return <><PageTitle eyebrow="Live analysis" title="Evaluate a synthetic transaction" description="The form is owned by the active model schema. Only returned feature fields are sent for evaluation." action={<StateBadge value={mutation.data?.execution_mode||"ready"}/>}/>{cfg.isLoading?<Loading label="Loading model-owned schema"/>:cfg.isError?<ErrorState retry={()=>cfg.refetch()}/>:<div className="grid gap-6 lg:grid-cols-[1fr_.72fr]"><Card><CardHeader><CardTitle className="flex items-center gap-2 text-base"><FlaskConical className="size-4 text-primary"/>Transaction features <span className="ml-auto text-xs font-normal text-muted-foreground">{schema.length} fields</span></CardTitle></CardHeader><CardContent><form onSubmit={submit} className="grid gap-4 sm:grid-cols-2">{schema.map((f:FeatureDefinition)=><div key={f.key} className="space-y-2"><Label htmlFor={f.key}>{f.label}{f.required&&<span className="ml-1 text-destructive">*</span>} {f.unit&&<span className="text-xs text-muted-foreground">({f.unit})</span>}</Label>{f.type==="select"&&f.options?.length?<Select value={values[f.key]||""} onValueChange={v=>setValues({...values,[f.key]:v})}><SelectTrigger id={f.key} data-testid={`input-feature-${f.key}`}><SelectValue placeholder={f.placeholder||"Select synthetic value"}/></SelectTrigger><SelectContent>{f.options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select>:<Input id={f.key} type={f.type==="number"?"number":"text"} placeholder={f.placeholder||"Synthetic value"} min={f.min??undefined} max={f.max??undefined} value={values[f.key]||""} onChange={(e:ChangeEvent<HTMLInputElement>)=>setValues({...values,[f.key]:e.target.value})} data-testid={`input-feature-${f.key}`}/>} {f.description&&<p className="text-[11px] text-muted-foreground">{f.description}</p>}</div>)}<div className="sm:col-span-2"><Button type="submit" disabled={mutation.isPending||!schema.length} className="w-full" data-testid="button-submit-analysis">{mutation.isPending?<><Activity className="mr-2 size-4 animate-pulse"/>Evaluating model…</>:<>Run QSVM analysis <ArrowRight className="ml-2 size-4"/></>}</Button></div></form></CardContent></Card><div className="space-y-6"><ScoreCard result={mutation.data}/>{mutation.isError&&<ErrorState retry={()=>mutation.reset()}/>} {mutation.data&&<Evidence result={mutation.data}/>}</div></div>}</> }
function Evidence({result}:{result:AnalyzeResponse}) { return <Card><CardHeader><CardTitle className="text-base">Evidence context</CardTitle></CardHeader><CardContent className="space-y-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Model</span><span className="font-mono text-xs" data-testid="text-model-used">{result.model_used}</span></div><div className="flex justify-between"><span className="text-muted-foreground">Request</span><span className="font-mono text-xs">{result.request_id||"Protected"}</span></div>{(result.signal_context||[]).map((x,i)=><div key={i} className="flex gap-2 rounded-md bg-muted p-2 text-xs"><Check className="size-4 shrink-0 text-primary"/>{x}</div>)}</CardContent></Card> }

function Benchmarks() { const q=useGetBenchmarks({query:{queryKey:getGetBenchmarksQueryKey()}}); return <><PageTitle eyebrow="Model integrity" title="Benchmark comparison" description="Comparable metrics on one shared split. Unavailable values stay unavailable — never represented as zero." action={q.data&&<StateBadge value={q.data.execution_mode}/>}/>{q.isLoading?<Loading label="Loading benchmark evaluation"/>:q.isError?<ErrorState retry={()=>q.refetch()}/>:<Card><CardHeader><CardTitle className="text-base">QSVM and classical baselines</CardTitle></CardHeader><CardContent className="overflow-x-auto"><Table><TableHeader><TableRow><TableHead>Model</TableHead><TableHead>ROC AUC</TableHead><TableHead>Precision</TableHead><TableHead>Recall</TableHead><TableHead>F1</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{(q.data?.benchmark_table||[]).map((r:BenchmarkRow,i)=><TableRow key={r.model} data-testid={`row-benchmark-${i}`}><TableCell className="font-semibold">{r.model}</TableCell>{["roc_auc","precision","recall","f1"].map(k=><TableCell key={k}>{r.status==="available"&&r[k as keyof BenchmarkRow]!=null?Number(r[k as keyof BenchmarkRow]).toFixed(3):<span className="text-muted-foreground">Unavailable</span>}</TableCell>)}<TableCell><StateBadge value={r.status}/>{r.note&&<p className="mt-1 max-w-48 text-xs text-muted-foreground">{r.note}</p>}</TableCell></TableRow>)}</TableBody></Table>{!q.data?.benchmark_table?.length&&<p className="py-8 text-center text-sm text-muted-foreground">No benchmark rows were returned.</p>}</CardContent></Card>}</> }
function Methodology() { return <><PageTitle eyebrow="How it works" title="A transparent path from features to review" description="The pipeline is explainable by design: model output is one input to an analyst’s decision, not an automated verdict."/><div className="grid gap-4 md:grid-cols-3">{[["01","Shape","The active model publishes the feature schema. The workspace renders and submits only those accepted fields."],["02","Score","QSVM evaluates the synthetic transaction in the execution mode reported by the service. Model identity travels with every result."],["03","Review","The score and signal context prioritize human review. Thresholds are context, not a substitute for investigation."]].map(([n,t,d])=><Card key={n}><CardContent className="p-6"><span className="font-mono text-sm text-primary">{n}</span><h2 className="mt-5 text-xl font-bold">{t}</h2><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{d}</p></CardContent></Card>)}</div><Card className="mt-6 border-accent/50 bg-accent/10"><CardContent className="flex gap-4 p-6"><CircleAlert className="size-5 shrink-0 text-accent-foreground"/><div><p className="font-semibold">Model caveats</p><p className="mt-1 text-sm text-muted-foreground">Synthetic demo results do not establish production performance, quantum advantage, or causal explanation. Treat missing benchmarks and non-live execution states honestly.</p></div></CardContent></Card></> }
function Demo() { const [,setLocation]=useLocation(); const scenarios=[["Baseline transfer","Low-variance synthetic transfer","Review context only"],["Velocity spike","Repeated short-window activity","Review recommended"],["Channel shift","New synthetic channel pattern","Inspect evidence"]]; return <><PageTitle eyebrow="Rehearsal mode" title="Prepared scenarios" description="Use these safe, anonymized prompts to rehearse the command-center flow before a live evaluation." action={<Badge variant="outline">Synthetic only</Badge>}/><div className="grid gap-4 md:grid-cols-3">{scenarios.map(([title,desc,badge],i)=><Card key={title} className="transition-transform hover:-translate-y-1"><CardContent className="p-6"><div className="flex items-center justify-between"><span className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-sm font-bold text-primary">0{i+1}</span><Badge variant="secondary">{badge}</Badge></div><h2 className="mt-6 font-bold">{title}</h2><p className="mt-2 text-sm text-muted-foreground">{desc}</p><Button variant="outline" className="mt-6 w-full" onClick={()=>setLocation("/analyze")} data-testid={`button-scenario-${i}`}>Open workspace <ArrowRight className="ml-2 size-4"/></Button></CardContent></Card>)}</div></> }
function App() { return <QueryClientProvider client={queryClient}><TooltipProvider><Shell><Switch><Route path="/" component={Home}/><Route path="/analyze" component={Analyze}/><Route path="/benchmarks" component={Benchmarks}/><Route path="/methodology" component={Methodology}/><Route path="/demo" component={Demo}/><Route component={NotFound}/></Switch></Shell></TooltipProvider><Toaster/></QueryClientProvider> }
export default App;